### PR TITLE
Remove redundant

### PR DESCRIPTION
**Pull request by ChenZhao44**
Multigraph backend was moved to Multigraphs.jl. Benchmarks were moved to quantum-benchmarks.

### CODE REVIEW

**Comment by Roger-luo** [comment]
I think you need to either export `ne` in Multigraph package or import it from `LightGraph` here. The tests are not passing at the moment.

**Comment by ChenZhao44** [comment]
> I think you need to either export `ne` in Multigraph package or import it from `LightGraph` here. The tests are not passing at the moment.

This error occurs because it used the older version of the Multigraphs. Could you please register a new version for the Multigraph package?

**Comment by ChenZhao44** [comment]
@Roger-luo Travis CI failed in Julia 1.0. Should we remove the support for the 1.0 version?

**Comment by Roger-luo** [comment]
yeah, let's remove 1.0 support

**Pull request merged**
