### PR TITLE
Trying to remove layout

### PR DESCRIPTION
**Pull request by ChenZhao44**
In this PR, I try to generate ZXLayout only when it is needed (plotting, converting ZXDiagram to circuits).

### CODE REVIEW

**Comment by Roger-luo** [comment]
cool, this looks much better! but I'm thinking maybe we should re-think about the layouts and integrate things with Quon, so they can share some implementation and move the plotting related code in seperate package (persumably just YaoPlots), to reduce the core functionality here.

**Comment by ChenZhao44** [comment]
I will merge it first after all tests passing. @Roger-luo

**Comment by Roger-luo** [comment]
need to have some more tests, the testcov is not happy

**Comment by ChenZhao44** [comment]
> need to have some more tests, the testcov is not happy

The PR will increase codecov now.

**Pull request merged**
